server:
  port: 8003

#spring的配置
spring:
  application:
    name: spring-cloud-provider-emp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.214:3306/sc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#mybatis配置文件
mybatis:
  type-aliases-package: com.zwb.sc.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

info:
  app.name: ${spring.application.name}--${server.port}
  company.name: amc